- name: ansible
  hosts: web
  become: yes
  tasks:
    - name: copy war to tomcat
      copy:
       src: "/var/snap/jenkins/4874/workspace/externalAnsible/target/MavenAnsibleWebApp.war"
       dest: "/opt/tomcat/webapps/MavenAnsibleWebApp.war"
       remote_src: no
    - name: automate tomcat
      systemd:
       name: tomcat
       state: restarted
